// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/matheusfm/go4lunch/api/handlers"
	"github.com/matheusfm/go4lunch/api/routers"
	"github.com/matheusfm/go4lunch/internal/product"
)

// Injectors from wire.go:

func SetupApplication() (*routers.SystemRoutes, error) {
	repository := product.NewRepository()
	handlersProduct := handlers.NewProduct(repository)
	systemRoutes := routers.NewSystemRoutes(handlersProduct)
	return systemRoutes, nil
}
